theme: jekyll-theme-midnight
title: "Gospel Lessons"
gitorg: "https://github.com/jm1021/gospelofjohn"
description: "When the word of God is taught and received by the Spirit, it has the power to change hearts and inspire conversion. It has a “more powerful effect upon the minds of the people than … anything else” (Alma 31:5)."
google_analytics:
twitter: "https://twitter.com/Ch_JesusChrist"
twitterid: "@Ch_JesusChrist"
webserver: "https://www.churchofjesuschrist.org/"
webserverid: "churchofjesuschrist"
