theme: jekyll-theme-midnight
title: "The Power of Spiritual Momentum"
gitorg: "https://github.com/jm1021/gospelofjohn"
description: "April 2022"
google_analytics:
twitter: "https://twitter.com/Ch_JesusChrist"
twitterid: "@Ch_JesusChrist"
webserver: "https://www.churchofjesuschrist.org/"
webserverid: "churchofjesuschrist"
